import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { BrowserRouter, Link, Navigate, Route, Routes, useNavigate } from 'react-router-dom';
import { api, getUser, logout, saveSession } from './lib/api.js';
import AdminEnrollments from './components/AdminEnrollments.jsx';
import './styles.css';

function Shell({ children }) {
  const navigate = useNavigate(); const user = getUser(); const [open, setOpen] = useState(false);
  function signOut(){ logout(); navigate('/login'); }
  return <><header className="nav"><Link className="brand" to="/">Course<span>Hub</span></Link><button className="menu" onClick={()=>setOpen(!open)} aria-label="Toggle navigation">☰</button><nav className={open?'open':''}><Link to="/courses" onClick={()=>setOpen(false)}>Courses</Link>{user && <Link to={user.role==='admin'?'/admin':'/dashboard'} onClick={()=>setOpen(false)}>Dashboard</Link>}{user ? <button className="linkbtn" onClick={signOut}>Logout</button> : <Link className="navcta" to="/login">Sign in</Link>}</nav></header>{children}<footer>© 2026 CourseHub · Built for Cognevance Level 2</footer></>
}
function Protected({ children, role }) { const user=getUser(); if(!user) return <Navigate to="/login" replace/>; if(role && user.role!==role) return <Navigate to={user.role==='admin'?'/admin':'/dashboard'} replace/>; if(!role && user.role==='admin') return <Navigate to="/admin" replace/>; return children; }
function Home(){ return <main><section className="hero"><div><p className="eyebrow">ONLINE LEARNING PLATFORM</p><h1>Learn skills that move your career forward.</h1><p className="lead">Discover practical courses, enroll in minutes, and track your progress from one responsive dashboard.</p><div className="actions"><Link className="primary" to="/courses">Explore courses</Link><Link className="secondary" to="/register">Create account</Link></div></div><div className="hero-card"><div className="orb">✓</div><h3>Learning progress</h3><div className="bar"><span style={{width:'72%'}}/></div><strong>72% completed</strong><p>Keep building your skills one lesson at a time.</p></div></section><section className="stats"><div><b>3+</b><span>Demo courses</span></div><div><b>2</b><span>User roles</span></div><div><b>100%</b><span>Responsive UI</span></div><div><b>REST</b><span>API architecture</span></div></section></main> }
function Login(){ const [form,setForm]=useState({email:'',password:''}); const [error,setError]=useState(''); const navigate=useNavigate(); async function submit(e){e.preventDefault();setError('');try{const d=await api('/api/auth/login',{method:'POST',body:JSON.stringify(form)});saveSession(d);navigate(d.user.role==='admin'?'/admin':'/dashboard')}catch(err){setError(err.message)}} return <Auth title="Welcome back" subtitle="Sign in to continue learning."><form onSubmit={submit}>{error&&<div className="alert">{error}</div>}<Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Password" type="password" value={form.password} onChange={v=>setForm({...form,password:v})}/><button className="primary full">Sign in</button><p className="hint">Demo student: student@example.com / Student@12345</p><p className="hint">No account? <Link to="/register">Create one</Link></p></form></Auth> }
function Register(){ const [form,setForm]=useState({name:'',email:'',password:''}); const [error,setError]=useState(''); const navigate=useNavigate(); async function submit(e){e.preventDefault();setError('');try{const d=await api('/api/auth/register',{method:'POST',body:JSON.stringify(form)});saveSession(d);navigate('/dashboard')}catch(err){setError(err.message)}} return <Auth title="Create your account" subtitle="Start learning at your own pace."><form onSubmit={submit}>{error&&<div className="alert">{error}</div>}<Field label="Full name" value={form.name} onChange={v=>setForm({...form,name:v})}/><Field label="Email" type="email" value={form.email} onChange={v=>setForm({...form,email:v})}/><Field label="Password" type="password" value={form.password} onChange={v=>setForm({...form,password:v})}/><button className="primary full">Create account</button></form></Auth> }
function Auth({title,subtitle,children}){return <main className="auth"><div className="authbox"><p className="eyebrow">COURSEHUB</p><h2>{title}</h2><p>{subtitle}</p>{children}</div></main>}
function Field({label,type='text',value,onChange,placeholder}){return <label className="field"><span>{label}</span><input required type={type} minLength={type==='password'?8:undefined} autoComplete={type==='email'?'email':type==='password'?'current-password':'name'} value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)}/></label>}
function Courses(){ const [courses,setCourses]=useState([]); const [q,setQ]=useState(''); const [category,setCategory]=useState(''); const [level,setLevel]=useState(''); const [msg,setMsg]=useState(''); const user=getUser(); async function load(){const p=new URLSearchParams({});if(q)p.set('search',q);if(category)p.set('category',category);if(level)p.set('level',level);const d=await api(`/api/courses?${p}`);setCourses(d.courses)} useEffect(()=>{load().catch(e=>setMsg(e.message))},[q,category,level]); async function enroll(id){try{await api(`/api/enrollments/${id}`,{method:'POST'});setMsg('Enrolled successfully.');}catch(e){setMsg(e.message)}} return <main className="page"><div className="pagehead"><div><p className="eyebrow">COURSE CATALOG</p><h2>Find your next course</h2></div></div><div className="filters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search courses, instructors..."/><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option><option>Web Development</option><option>Backend</option><option>Data Science</option></select><select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></div>{msg&&<div className="notice">{msg}</div>}<div className="grid">{courses.map(c=><article className="course" key={c._id}><div className="course-top"><span>{c.category}</span><span>{c.level}</span></div><h3>{c.title}</h3><p>{c.description}</p><div className="meta"><span>{c.durationHours}h</span><span>{c.instructor}</span></div>{user?.role==='student'&&<button className="primary full" onClick={()=>enroll(c._id)}>Enroll</button>}</article>)}</div>{!courses.length&&<div className="empty">No courses match your filters.</div>}</main> }
function Dashboard(){ const [items,setItems]=useState([]); const [error,setError]=useState(''); async function load(){try{const d=await api('/api/enrollments/mine');setItems(d.enrollments)}catch(e){setError(e.message)}} useEffect(()=>{load()},[]); async function update(id,value){try{await api(`/api/enrollments/${id}/progress`,{method:'PATCH',body:JSON.stringify({progress:Number(value)})});load()}catch(e){setError(e.message)}} const completed=items.filter(i=>i.completed).length; return <main className="page"><div className="pagehead"><div><p className="eyebrow">STUDENT DASHBOARD</p><h2>Your learning journey</h2></div><div className="mini-stat"><b>{completed}/{items.length}</b><span>Completed</span></div></div>{error&&<div className="alert">{error}</div>}<div className="grid">{items.map(i=><article className="course progress-card" key={i._id}><span className="pill">{i.course.level}</span><h3>{i.course.title}</h3><p>{i.course.description}</p><div className="bar"><span style={{width:`${i.progress}%`}}/></div><div className="progress-row"><b>{i.progress}%</b><span>{i.completed?'Completed':'In progress'}</span></div><label className="range">Update progress <input type="range" min="0" max="100" value={i.progress} onChange={e=>update(i._id,e.target.value)}/></label></article>)}</div>{!items.length&&<div className="empty">You have no enrollments yet. <Link to="/courses">Browse courses</Link>.</div>}</main> }
function Admin(){ const [courses,setCourses]=useState([]); const [enrollments,setEnrollments]=useState([]); const [form,setForm]=useState({title:'',description:'',instructor:'',category:'Web Development',level:'Beginner',durationHours:10,lessons:['Lesson 1','Lesson 2']}); const [msg,setMsg]=useState(''); async function load(){const [c,e]=await Promise.all([api('/api/courses/admin/all'),api('/api/enrollments/admin/all')]);setCourses(c.courses);setEnrollments(e.enrollments)} useEffect(()=>{load().catch(e=>setMsg(e.message))},[]); async function create(e){e.preventDefault();try{await api('/api/courses',{method:'POST',body:JSON.stringify({...form,durationHours:Number(form.durationHours)})});setMsg('Course created.');load()}catch(e){setMsg(e.message)}} async function unpublish(id){await api(`/api/courses/${id}`,{method:'DELETE'});load()} return <main className="page"><div className="pagehead"><div><p className="eyebrow">ADMIN CONSOLE</p><h2>Manage your academy</h2></div><div className="mini-stat"><b>{enrollments.length}</b><span>Enrollments</span></div></div>{msg&&<div className="notice">{msg}</div>}<section className="admin-grid"><form className="panel" onSubmit={create}><h3>Add course</h3><Field label="Title" value={form.title} onChange={v=>setForm({...form,title:v})}/><label className="field"><span>Description</span><textarea required value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><Field label="Instructor" value={form.instructor} onChange={v=>setForm({...form,instructor:v})}/><div className="two"><Field label="Category" value={form.category} onChange={v=>setForm({...form,category:v})}/><Field label="Hours" type="number" value={form.durationHours} onChange={v=>setForm({...form,durationHours:v})}/></div><label className="field"><span>Level</span><select value={form.level} onChange={e=>setForm({...form,level:e.target.value})}><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><button className="primary full">Create course</button></form><div className="panel"><h3>Courses</h3>{courses.map(c=><div className="admin-item" key={c._id}><div><b>{c.title}</b><small>{c.category} · {c.level}</small></div>{c.published&&<button className="ghost" onClick={()=>unpublish(c._id)}>Unpublish</button>}</div>)}</div></section></main> }
function App(){return <Shell><Routes><Route path="/" element={<Home/>}/><Route path="/courses" element={<Courses/>}/><Route path="/login" element={<Login/>}/><Route path="/register" element={<Register/>}/><Route path="/dashboard" element={<Protected><Dashboard/></Protected>}/><Route path="/admin" element={<Protected role="admin"><><Admin/><AdminEnrollments/></></Protected>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></Shell>}

createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>);
